# Generated by Django 3.2.8 on 2021-10-28 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('item_code', models.IntegerField(primary_key=True, serialize=False)),
                ('food', models.CharField(max_length=16, unique=True)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('item_category_code', models.IntegerField(primary_key=True, serialize=False)),
                ('item_category', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_code', models.CharField(max_length=2)),
                ('kind', models.CharField(max_length=16)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='prices.food')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCls',
            fields=[
                ('product_cls_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('product_cls', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRank',
            fields=[
                ('product_rank_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('product_rank', models.CharField(max_length=8)),
                ('grade_rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('market', models.CharField(max_length=16)),
                ('price', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='prices.country')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='prices.food')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='prices.kind')),
                ('product_cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='prices.productcls')),
                ('product_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='prices.productrank')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='prices.unit')),
            ],
        ),
        migrations.CreateModel(
            name='FoodProductRanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ranks', to='prices.food')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ranks', to='prices.kind')),
                ('product_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='prices.productrank')),
            ],
        ),
        migrations.CreateModel(
            name='FoodComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prices.food')),
                ('like_users', models.ManyToManyField(related_name='like_food_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prices.itemcategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='like_users',
            field=models.ManyToManyField(related_name='like_foods', to=settings.AUTH_USER_MODEL),
        ),
    ]
