# Generated by Django 3.2.8 on 2021-12-09 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('item_code', models.IntegerField(primary_key=True, serialize=False)),
                ('food', models.CharField(max_length=16, unique=True)),
                ('wholesale_unit', models.CharField(max_length=8, null=True)),
                ('retail_unit', models.CharField(max_length=8, null=True)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('item_category_code', models.IntegerField(primary_key=True, serialize=False)),
                ('item_category', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_code', models.CharField(max_length=2)),
                ('kind', models.CharField(max_length=16)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='prices.food')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCls',
            fields=[
                ('product_cls_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('product_cls', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRank',
            fields=[
                ('product_rank_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('product_rank', models.CharField(max_length=8)),
                ('grade_rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='prices.country')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='prices.kind')),
                ('product_cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='prices.productcls')),
                ('product_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='prices.productrank')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='prices.pricecondition')),
            ],
        ),
        migrations.AddField(
            model_name='kind',
            name='product_ranks',
            field=models.ManyToManyField(blank=True, related_name='kinds', to='prices.ProductRank'),
        ),
        migrations.CreateModel(
            name='FoodComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=255)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prices.food')),
                ('like_users', models.ManyToManyField(related_name='like_food_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='food',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prices.itemcategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='like_users',
            field=models.ManyToManyField(related_name='like_foods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pricecondition',
            index=models.Index(fields=['kind', 'country', 'product_rank', 'product_cls'], name='prices_pric_kind_id_340765_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricecondition',
            unique_together={('kind', 'country', 'product_rank', 'product_cls')},
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['condition', 'date'], name='prices_pric_conditi_509064_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('condition', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='kind',
            unique_together={('food', 'kind_code')},
        ),
    ]
