# Generated by Django 3.2.8 on 2021-10-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='market',
            field=models.CharField(max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='item_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='kind_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='product_cls',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='product_rank',
            field=models.IntegerField(),
        ),
    ]
