# Generated by Django 3.2.8 on 2021-12-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
    ]
