# Generated by Django 3.2.8 on 2021-12-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_pricecondition_prices_exist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricecondition',
            old_name='prices_exist',
            new_name='prices_exists',
        ),
    ]
