# Generated by Django 3.2.8 on 2021-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_rename_prices_exist_pricecondition_prices_exists'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pricecondition',
            name='prices_pric_kind_id_340765_idx',
        ),
        migrations.AddIndex(
            model_name='pricecondition',
            index=models.Index(fields=['kind', 'country', 'product_rank', 'product_cls', 'prices_exists'], name='prices_pric_kind_id_294a9e_idx'),
        ),
    ]
